# Generated by Django 5.0.6 on 2024-06-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('student', models.ManyToManyField(to='students.student')),
            ],
        ),
    ]
